### ISSUE TITLE
accountchooser.com is shutting down

### ISSUE THREAD

**Issue by webstermath** [firebase/firebaseui-web-react#104]
I am getting this warning when using firebaseui-web-react:

> 1.chunk.js:97796  [  1.714s] [firebaseui] AccountChooser.com will be operating in "universal opt-out" mode starting July 31st, 2020, it should no longer be used as a CredentialHelper. Learn more at https://accountchooser.net/developers

**Comment by bojeil-google** [comment]
Yeah, if you need to stop using `accountchooser.com` as it is being deprecated. Click [here](https://github.com/firebase/firebaseui-web#accountchoosercom) to learn more.

**Comment by webstermath** [comment]
Thank you.
