### ISSUE TITLE
Update firebase peer dependency to support 8.x.x

### ISSUE THREAD

**Issue by matamatanot** [firebase/firebaseui-web-react#114]
https://github.com/firebase/firebase-js-sdk/pull/3982

Error with firebase 8.0.0

```
node_modules/firebaseui/dist/esm.js
--
Attempted import error: 'app' is not exported from 'firebase/app' (imported as 'firebase').
```

**Comment by lookfirst** [comment]
https://github.com/firebase/firebaseui-web/commit/39230c67335b653b376c914d05189e8c87f91004

**Comment by bojeil-google** [comment]
Hey @jhuleatt can you help with this issue or assign to the right person?

**Comment by gvillenave** [comment]
Any update?

**Comment by gvillenave** [comment]
Just submitted PR to update the dependency here: https://github.com/firebase/firebaseui-web-react/pull/115

**Comment by masjugo** [comment]
I'm getting this Error when trying to install it in a gatsby project

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-hello-world@0.1.0
npm ERR! Found: firebase@8.1.1
npm ERR! node_modules/firebase
npm ERR!   firebase@"^8.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer firebase@">=6.3.4 <8" from react-firebaseui@4.1.0
npm ERR! node_modules/react-firebaseui
npm ERR!   react-firebaseui@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by lookfirst** [comment]
I just kept my firebase dependency at 7x until this is resolved.

**Comment by CLantigua2** [comment]
Ran into the same issue. Installed firebase and tried to then install react-firebaseui

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: chess_game@0.1.0
npm ERR! Found: firebase@8.1.2
npm ERR! node_modules/firebase
npm ERR!   firebase@"^8.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer firebase@">=6.3.4 <8" from react-firebaseui@4.1.0
npm ERR! node_modules/react-firebaseui
npm ERR!   react-firebaseui@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by lookfirst** [comment]
Wow, thanks @brendanmc6 @jhuleatt !

**Comment by ulisses-cruz** [comment]
looks like, the problem returned

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving:
npm ERR! Found: firebase@9.3.0
npm ERR! node_modules/firebase
npm ERR!   peer firebase@">= 9.0.0" from react-firebase-hooks@4.0.1
npm ERR!   node_modules/react-firebase-hooks
npm ERR!     react-firebase-hooks@"^4.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-firebaseui@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: firebase@8.10.0
npm ERR! node_modules/firebase
npm ERR!   peer firebase@"^8.2.4" from react-firebaseui@5.0.2
npm ERR!   node_modules/react-firebaseui
npm ERR!     react-firebaseui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```
