### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by thien-do** [firebase/firebaseui-web-react#116]
React 17 release notes: https://reactjs.org/blog/2020/10/20/react-v17.html (not many breaking changes)

Related code: https://github.com/firebase/firebaseui-web-react/blob/18862d2ae458c6b031d394f958870a108817ae7c/package.json#L32

**Comment by HugoGresse** [comment]
See https://github.com/firebase/firebaseui-web-react/pull/122
(already released in canary)
