### ISSUE TITLE
Multiple Instances of FirebaseAuth Doesn't Work

### ISSUE THREAD

**Issue by johnkmzhou** [firebase/firebaseui-web-react#12]
I tried to create multiple instances of FirebaseAuth by following https://github.com/firebase/firebaseui-web-react#using-multiple-instances and only the second instance gets rendered. Currently, I'm using react-firebaseui 1.0.10.

If that's not possible, then a possible solution could be a prop that can be used to trigger the start() reset() function.

**Comment by nicolasgarnier** [comment]
@johnkmzhou my bad it looks like only one firebaseui instance can run at a time. @bojeil-google can you confirm that?

For now I'll remove that section of the README

**Comment by bojeil-google** [comment]
Yes that is correct. Having multiple instances rendered at the same time is not practical and results in some weird situations when redirect operations are being processed. 

You can only render one at a time. If you render a new one, we automatically reset the existing one. If the existing one is pending some operation, we also log a warning:
https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/authui.js#L491

We provide public APIs to `reset`/`destroy` an existing instance.
We also provide a `firebaseui.auth.AuthUI.getInstance(opt_appId)` to help retrieve the AuthUI instance corresponding to `opt_appId`.

**Comment by nicolasgarnier** [comment]
Thanks @bojeil-google closing.
