### ISSUE TITLE
how to get Facebook accessToken ?

### ISSUE THREAD

**Issue by soly2014** [firebase/firebaseui-web-react#120]

**Comment by jhuleatt** [comment]
Here's an example that may help https://github.com/firebase/snippets-web/blob/fd06c854d0efaa57cf05ad89a42f77bee9510eab/auth/facebook.js#L35-L36

**Comment by csulit** [comment]
> Here's an example that may help https://github.com/firebase/snippets-web/blob/fd06c854d0efaa57cf05ad89a42f77bee9510eab/auth/facebook.js#L35-L36

still no good obtaining access token.
