### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by binajmen** [firebase/firebaseui-web-react#127]
A big thank you for providing this FirebaseUI wrapper, very helpful ❤️

Is there a way to specify the locale to enable i18n of the interface? It is possible when using the [CDN option](https://github.com/firebase/firebaseui-web#localized-widget). Would love to hear how we can achieve the same with the react wrapper.

**Comment by jhuleatt** [comment]
Hey @binajmen, i18n/localization is tracked in #21.

[This comment](https://github.com/firebase/firebaseui-web-react/issues/21#issuecomment-606625278) describes a potential workaround.
