### ISSUE TITLE
vue-cli-service: not found

### ISSUE THREAD

**Issue by linuxandroid-xyz** [firebase/firebaseui-web-react#128]
arthur@Arthur:~/Desktop/sub-web-master$ firebase init

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /home/arthur/Desktop/sub-web-master

? Which Firebase CLI features do you want to set up for this folder? Press Space to select features, then Enter to confirm your choices. Hosting: Configure and deploy Firebase Hosting sites

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add, 
but for now we'll just set up a default project.

? Please select an option: Use an existing project
? Select a default Firebase project for this directory: cnspecialcolor (cnspecialcolor)
i  Using project cnspecialcolor (cnspecialcolor)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

? What do you want to use as your public directory? public
? Configure as a single-page app (rewrite all urls to /index.html)? Yes
? Set up automatic builds and deploys with GitHub? Yes
? File public/index.html already exists. Overwrite? Yes
✔  Wrote public/index.html

i  Didn't detect a .git folder. Assuming /home/arthur/Desktop/sub-web-master is the project root.
i  Authorizing with GitHub to upload your service account to a GitHub repository's secrets store.

Visit this URL on this device to log in:
https://github.com/login/oauth/authorize?client_id=89cf50f02ac6aaed3484&state=856193655&redirect_uri=http%3A%2F%2Flocalhost%3A9005&scope=read%3Auser%20repo%20public_repo

Waiting for authentication...

✔  Success! Logged into GitHub as linuxandroid-xyz

? For which GitHub repository would you like to set up a GitHub workflow? (format: user/repository) linuxandroid-xyz/sub-web

✔  Created service account github-action-342187799 with Firebase Hosting admin permissions.
✔  Uploaded service account JSON to GitHub as secret FIREBASE_SERVICE_ACCOUNT_CNSPECIALCOLOR.
i  You can manage your secrets at https://github.com/linuxandroid-xyz/sub-web/settings/secrets.

? Set up the workflow to run a build script before every deploy? Yes
? What script should be run before every deploy? npm run build

✔  Created workflow file /home/arthur/Desktop/sub-web-master/.github/workflows/firebase-hosting-pull-request.yml
? Set up automatic deployment to your site's live channel when a PR is merged? Yes
? What is the name of the GitHub branch associated with your site's live channel? master

✔  Created workflow file /home/arthur/Desktop/sub-web-master/.github/workflows/firebase-hosting-merge.yml

i  Action required: Visit this URL to revoke authorization for the Firebase CLI GitHub OAuth App:
https://github.com/settings/connections/applications/89cf50f02ac6aaed3484
i  Action required: Push any new workflow file(s) to your repo

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
arthur@Arthur:~/Desktop/sub-web-master$ npm run build

> sub-web@0.1.0 build
> vue-cli-service build

sh: 1: vue-cli-service: not found
arthur@Arthur:~/Desktop/sub-web-master$ yarn build
yarn run v1.22.10
$ vue-cli-service build
/bin/sh: 1: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
arthur@Arthur:~/Desktop/sub-web-master$ sudo npm run build
[sudo] password for arthur: 

> sub-web@0.1.0 build
> vue-cli-service build

sh: 1: vue-cli-service: not found
arthur@Arthur:~/Desktop/sub-web-master$ sudo npm run build

> sub-web@0.1.0 build
> vue-cli-service build

sh: 1: vue-cli-service: not found
arthur@Arthur:~/Desktop/sub-web-master$ sudo npm run build

> sub-web@0.1.0 build
> vue-cli-service build

sh: 1: vue-cli-service: not found
arthur@Arthur:~/Desktop/sub-web-master$ firebase  deploy

=== Deploying to 'cnspecialcolor'...

i  deploying hosting
i  hosting[cnspecialcolor]: beginning deploy...
i  hosting[cnspecialcolor]: found 3 files in public
✔  hosting[cnspecialcolor]: file upload complete
i  hosting[cnspecialcolor]: finalizing version...
✔  hosting[cnspecialcolor]: version finalized
i  hosting[cnspecialcolor]: releasing new version...
✔  hosting[cnspecialcolor]: release complete

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/cnspecialcolor/overview
Hosting URL: https://cnspecialcolor.web.app
arthur@Arthur:~/Desktop/sub-web-master$ npm run build

> sub-web@0.1.0 build
> vue-cli-service build

sh: 1: vue-cli-service: not found
arthur@Arthur:~/Desktop/sub-web-master$ yarn build
yarn run v1.22.10
$ vue-cli-service build
/bin/sh: 1: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
arthur@Arthur:~/Desktop/sub-web-master$ sudo yarn build
yarn run v1.22.10
$ vue-cli-service build
/bin/sh: 1: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
arthur@Arthur:~/Desktop/sub-web-master$

**Comment by jhuleatt** [comment]
doesn't appear to be related to firebaseui-web-react
