### ISSUE TITLE
Support create-react-app

### ISSUE THREAD

**Issue by shawnlauzon** [firebase/firebaseui-web-react#13]
According to the docs:

> The FirebaseAuth component needs a global CSS to get proper styling. The CSS is already imported within FirebaseAuth. If you are using webpack you'll need to add CSS loaders

Unfortunately it's my understanding that create-react-app doesn't support this without ejecting. Is this accurate? I would love for there to be some (even hacky) way to get the Authentication component to look good without ejecting.

**Comment by nicolasgarnier** [comment]
I just added a component which includes the CSS. If you use `StyledFirebaseAuth` rather than `FirebaseAuth` the CSS is already incorporated in the component and there is no need to use CSS loaders.

Please use the lates version (v1.1.0) and refer to the README for instructions.

**Comment by shawnlauzon** [comment]
Great, thanks! I had stopped using this component, but now that this is fixed I'll check it out again when I can :)
