### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by OrhanTozan** [firebase/firebaseui-web-react#133]
According to this project's GitHub releases, last stable release (v4.0.0) was 4 aug 2019. In the meanwhile, firebase/fireabaseui-web got newer versions while the react wrapper still lags behind. 

The NPM page also speaks by the way about a 5.0.0 canary version, but can't find any documentation anywhere about it's source code...

**Comment by OrhanTozan** [comment]
CC'ing the main contributor @nicolasgarnier.

**Comment by nicolasgarnier** [comment]
Thanks for the heads up!

I have left the Firebase project for a while now. I'll ping some Firebase colleagues si they can give you an update.

**Comment by OrhanTozan** [comment]
Thanks for responding @nicolasgarnier. Got any update on that update?

**Comment by zackdotcomputer** [comment]
I see @bojeil-google has started merging in some dependencies updates. Hopefully this means things are going to get unstuck soon and we can, for example, promote the `canary` to a proper 5.0 release?

**Comment by Andrew-web-coder** [comment]
Is this project dead again? I tried to start fresh a project and got this:

```
Found: firebase@8.4.1
npm ERR! node_modules/firebase
npm ERR!   firebase@"^8.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer firebase@">=6.3.4 <8" from react-firebaseui@4.1.0
```

**Comment by Andrew-web-coder** [comment]
I even tried completely fresh install and got

```
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@">=15 <17" from react-firebaseui@4.1.0
npm ERR!   node_modules/react-firebaseui
npm ERR!     react-firebaseui@"^4.1.0" from the root project
npm ERR!   react@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-dom@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"*" from the root project
```

so it seems this project is completely dead :(

**Comment by zackdotcomputer** [comment]
@Andrew-web-coder I do worry this project is dead, but not because of that. I think that’s because of the new NPM dependency management behavior being so strict. Can you try again as `npm install --legacy-peer-deps`?

**Comment by Andrew-web-coder** [comment]
I think this is the first indicator that active maintainers have left this project long time ago :( Maybe I should apply here for a job :D

**Comment by jhuleatt** [comment]
`react-firebaseui@5.0.1` is now available on npm

**Comment by OrhanTozan** [comment]
@jhuleatt Thanks, that's awesoem! Hope we can keep this project updated along the way😅
