### ISSUE TITLE
Do not import CSS

### ISSUE THREAD

**Issue by matteoturini** [firebase/firebaseui-web-react#150]
https://nextjs.org/docs/messages/css-npm

You should leave it up to the user.

NextJS does not allow this behavior, how would I fix it?

**Comment by matteoturini** [comment]
sorry i am just very stupid

**Comment by fabn** [comment]
@matteoturini I got the same issue how did you solve that?

**Comment by paymog** [comment]
how did you fix your issue? I'm running into a similar problem

**Comment by raaaahman** [comment]
I had a similar issue. The problem was that I was using:

```javascript
import { StyledFirebaseAuth } from "react-firebaseui";
```
instead of:

```javascript
import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth";
```
Don't ask me why both syntax resolve differently though...
