### ISSUE TITLE
Add new version for testing v9

### ISSUE THREAD

**Issue by ajonp** [firebase/firebaseui-web-react#154]
It appears we have a solid test in 

```
"firebaseui": "^0.600.0-rc.0",
```
I would like to be able to test this version of the UI with React.

https://github.com/firebase/firebaseui-web/issues/837#issuecomment-902565759

**Comment by jhuleatt** [comment]
Now available in [6.0.0](https://github.com/firebase/firebaseui-web-react/releases/tag/v6.0.0)!
