### ISSUE TITLE
Installation fails with "firebase": "^9.0.0"

### ISSUE THREAD

**Issue by SergiiMost** [firebase/firebaseui-web-react#156]
Hi, 

`npm install --save react-firebaseui`  fails with  "firebase": "^9.0.0".

Here is the error: 
```

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.1.0
npm ERR! Found: firebase@9.0.0
npm ERR! node_modules/firebase
npm ERR!   firebase@"^9.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer firebase@"^8.2.4" from react-firebaseui@5.0.2
npm ERR! node_modules/react-firebaseui
npm ERR!   react-firebaseui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```
Thanks.

**Comment by nsadeh** [comment]
Also ran into this issue, would be grateful to be able to use Firebase 9 with the React UI.

**Comment by KristianRykkje** [comment]
Looks like firebase ui won't be upgrade to use v9 any time soon.
https://github.com/firebase/firebaseui-web/issues/877

**Comment by jhuleatt** [comment]
react-firebaseui version 6 (with support for FirebaseUI v6 and Firebase v9 compat) is now available on npm! If you'd like some more background on why this library doesn't support the v9 modular syntax at this time, please take a look at this comment: https://github.com/firebase/firebaseui-web-react/pull/158#issuecomment-964269348

**Comment by fabyeah** [comment]
I'm using Firebase v9 modular and can't get this react-firebaseui version 6 to work with the Auth emulator. I guess it will work if your emulator is set up for the compat library, but not if set up for v9 modular.

**Comment by egisz** [comment]
> I'm using Firebase v9 modular and can't get this react-firebaseui version 6 to work with the Auth emulator. I guess it will work if your emulator is set up for the compat library, but not if set up for v9 modular.
same boat, did you find solution?

**Comment by fabyeah** [comment]
> > same boat, did you find solution?

no, i keep using v8 🤷
