### ISSUE TITLE
Cannot Install in React 18.2

### ISSUE THREAD

**Issue by thanhtutzaw** [firebase/firebaseui-web-react#176]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: too@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=15 <=17" from react-firebaseui@6.0.0
npm ERR! node_modules/react-firebaseui
npm ERR!   react-firebaseui@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by SKR789123** [comment]
you can continue with adding --legacy-peer-deps as instructed. "npm i react-firebaseui --legacy-peer-deps " hoping there won't be any breaking changes

**Comment by bdytx5** [comment]
> npm i react-firebaseui --legacy-peer-deps

there is no instruction for this on the repo.

**Comment by svArpit** [comment]
it works though

**Comment by unshah** [comment]
It works, thanks!

**Comment by filipencus** [comment]
it doesn't work when executing ionic capacitor add    :(
