### ISSUE TITLE
Using componentDidMount instead of componentWillMount

### ISSUE THREAD

**Issue by kristof0425** [firebase/firebaseui-web-react#19]
The next major version of React is going to [deprecate `componentWillMount`](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md). Because of this, the next minor version (`v16.3`) is renaming `componentWillMount` to  `UNSAFE_componentWillMount`.

I saw in the README, at the `using FUIWR with local state` section, that `componentWillMount` lifecycle method is used for listening to Firebase and setting local state.

I suggest that the README should support the use of `componentDidMount` method to be up to date for next version releases of React.

**Comment by kristof0425** [comment]
I'd love to make a PR for this though, but before that, I just wanted to hear your opinions. 🙂

**Comment by nicolasgarnier** [comment]
Hey @kristof0425!

Yes that would work too :) Please send a PR. Can you also change [the example](https://github.com/firebase/firebaseui-web-react/blob/master/example/src/App.jsx) at the same time please?

Cheers!
