### ISSUE TITLE
FirebaseAuth appears blank after successfully logging in and then signing out

### ISSUE THREAD

**Issue by garyforsterio** [firebase/firebaseui-web-react#25]
Hello,

I'm finding that, if I sign in using the `FirebaseAuth` component and in the same session logout (using `firebase.auth().signOut()` ), when I try to render the component again, for example for the next user to sign in, the component is blank.

![image](https://user-images.githubusercontent.com/14568655/38015832-0dc2d7ca-32a8-11e8-9b00-c2ba8da8da6b.png)
The `#firebaseui_container` is in the DOM Tree but has no content.

I've seen the previous issue [here](https://github.com/firebase/firebaseui-web-react/issues/12) and thought they might be related so tried using the `firebaseui.auth.AuthUI.getInstance(opt_appId)` method to obtain the AuthUI instance and reset it, however that did not fix the problem.

I did however notice that when inspecting the instance, on the second time, one of the fields is `callback` rather than `passwordSignIn`. I've attached screenshots

![first time works](https://user-images.githubusercontent.com/14568655/38015704-91367504-32a7-11e8-8add-bcc98a209518.png)
![second time doesn t](https://user-images.githubusercontent.com/14568655/38015703-910c4356-32a7-11e8-885a-194b05b7e15c.png)

Here is my UI config
```js
  uiConfig = {
    signInFlow: 'popup',
    signInOptions: [firebase.auth.EmailAuthProvider.PROVIDER_ID],
    callbacks: {
      // Avoid redirects after sign-in.
      signInSuccess: () => false
    }
  };
```

I'm using Redux and React-router if that could have any effect. 

Many thanks

**Comment by nicolasgarnier** [comment]
Could you check that there are not 2 instances of firebaseUI that would be rendered? (that was the issue with the other issue you pointed to). make sure there are no 2 elements with ID "firebaseui_container".

Could you also show the code/markup where you render the `<FirebaseAuth>` ? 

Not sure if you have done that already but could also try running the [example app](https://github.com/firebase/firebaseui-web-react/blob/master/example/src/App.jsx) it's working well (or at least it was when I tried :)). Just  to make sure this works on your setup.

**Comment by nicolasgarnier** [comment]
OK I just released v1.2.3 Could you please try with this new version? There might be a case if the component is not unmounted and you sign-out then we'd need to reset it and I added some logic for that. Let me know!

**Comment by garyforsterio** [comment]
@nicolasgarnier thanks for the quick response. Just pulled down that patch but unfortunately it doesn't have any effect, however I've found the problem now.

It only seems to effect the `firebase.auth.EmailAuthProvider.PROVIDER_ID` option so when running your demo the problem didn't appear. When changing the source code in your example to this sign in option I had the same problem.

I hadn't noticed that by default the widget uses account chooser as a credential helper. What was happening was that chrome was blocking any third-party cookies to be set (see image below) and this somehow stopped me being redirected to account chooser on the first sign in. Not exactly sure why but when trying to login for a second time this was then stopping the email login widget from displaying.

![image](https://user-images.githubusercontent.com/14568655/38069054-52ef4c28-334f-11e8-905e-6ce8a2377fd1.png)

I've found that either allowing this third-party cookie or disabling the credential helper using the option `credentialHelper: firebaseui.auth.CredentialHelper.NONE` fixes this. Although, as I expect other users are also blocking third-party cookies I have chosen to disable the credential helper.

Thanks for you help, not sure if it's worth making a note of the credential helpers shortcomings in the documentation.

**Comment by nicolasgarnier** [comment]
Sweet, thanks for looking into this @garyforsterio 

@bojeil-google do you have any idea what's causing this bug? Any ways not to use cookies in this case maybe?

**Comment by bojeil-google** [comment]
Is this specific to accountchooser.com? Disabling it should bypass it.

**Comment by nicolasgarnier** [comment]
Yup disabling it will bypass it but:

I just tried on my chrome and I didn't get any issue with the account chooser. But it looks like some portion of users (like @garyforsterio) are disabling 3rd party cookies, which is causing this issue. It's not possible for developers to be user all of their users will have 3rd party cookies enabled. Users usually do it to [disable tracking by advertisers](https://www.cnet.com/how-to/disable-third-party-cookies-in-ie-firefox-and-google-chrome/) so this could impact some percentage of users.

Maybe we could detect this error and fallback automatically to no-helpers, especially since the account chooser is now the default.

**Comment by wti806** [comment]
@garyforsterio  When 3rd party cookie is disabled, did you see error code: "auth/unsupported-persistence-type", message: "The current environment does not support the specified persistence type." in console?

**Comment by nicolasgarnier** [comment]
@garyforsterio weirdly I tried with 3rd-party cookies disabled and the account chooser was simply skipped on Chrome. Let's still try to replicate this. Could you give me a bit more details about your setup for instance which version of Chrome were you using? Any other special settings you could think of?

**Comment by garyforsterio** [comment]
@wti806 no I didn't see any errors.

@nicolasgarnier yes logging in one time works fine. As you said the account chooser is skipped and there aren't any issues. However for some reason, after logging in, if you then logout and try to sign in again in the same session, i.e. the second time you try to authenticate in one session, something happens and the credentials form and widget no longer render. This can be replicated using the example code and replacing the `signinOptions` to `signInOptions: [firebase.auth.EmailAuthProvider.PROVIDER_ID]`

**Comment by soccer1mt** [comment]
I am still having this issue.  Has there been any resolution on how to get the widget to come back after signing in then signing out?

**Comment by FrederickIge** [comment]
Same issue here. I have firebaseUI on both my login and register pages. Only shows on one page.
