### ISSUE TITLE
[Question] Select a default provider

### ISSUE THREAD

**Issue by schettino** [firebase/firebaseui-web-react#26]
Is there any way to select a provider to be shown as default?

**Comment by nicolasgarnier** [comment]
Do you mean you'd like to display only one option with an link to display more options? Maybe have an element displayed with the "default" options for instance this would be the config for Facebook:

```js
uiConfig = {
    // Popup signin flow rather than redirect flow.
    signInFlow: 'popup',
    // We will display Google and Facebook as auth providers.
    signInOptions: [
      firebase.auth.FacebookAuthProvider.PROVIDER_ID
    ],
    callbacks: {
      // Avoid redirects after sign-in.
      signInSuccessWithAuthResult: () => false
    }
  };
```

Only the Facebook button would be displayed. You could add a link or button below that says "Show More" who would replace the element with a different one with a config that contains all the options. Just an idea.
