### ISSUE TITLE
Uncaught TypeError: Cannot read property 'navigator' of undefined

### ISSUE THREAD

**Issue by ObiKerui** [firebase/firebaseui-web-react#27]
I'm getting a blank page and the following stace trace error in my browser console...

![screenshotfirebaseui](https://user-images.githubusercontent.com/6961234/38681611-fec4787c-3e60-11e8-8059-ccb270a2c15a.png)

I have created an npm module which uses react-firebaseui. My npm module is exported as a 'umd library' using webpack. When I install this module into my main react project I am getting this error. I don't get this same error if I install react-firebaseui directly into my main react project however. The error is caused when I include either the 'FirebaseAuth' or 'StyleFirebaseAuth' components.

'navigator' seems to be a property that should be attached to the 'window' object. Is it possible the error is caused because 'window' is not defined?

**Comment by nicolasgarnier** [comment]
@ObiKerui, `react-firebaseui` is currently just a wrapper around `firebaseui`.

The error seems to come from `firebaseui` (that's where npm.js is). And `firebaseui` needs to be run in a browser environment where since it uses things like `window`. Not sure why `window` is not available in the environment though.

**Comment by ObiKerui** [comment]
I found the problem was to do with `react-firebaseui` being packaged inside the `npm umd` library module I was creating with `webpack`. I fixed the issue in `webpack` by marking `firebase` as an external module and a peer dependency in the project `package.json` file. Perhaps something in the way `webpack` was packaging `firebase` was causing the required `window` object to be renamed and lost? Anyway, hope this helps anyone who encounters this problem in future.

**Comment by sturmenta** [comment]
What I did was:

- Do not use the latest version of firebase, but the [version that indicate that you use](https://firebase.google.com/docs/firestore/quickstart?hl=es-419)
`npm install firebase@4.12.1 --save`

- Replace

```javascript
import * firebase from 'firebase';
import '@ firebase / firestore';
import '@ firebase / messaging';
```

by

```javascript
import * firebase from 'firebase';
import 'firebase / firestore';
import 'firebase / messaging';
```

- `npm i -S @ firebase / firestore`` npm i -S @ firebase / messaging`

And everything worked correctly!
