### ISSUE TITLE
Error "The current environment does not support the specified persistence type." is shown when StyledAuthComponent is used in electron app

### ISSUE THREAD

**Issue by ghost** [firebase/firebaseui-web-react#30]
I am trying to use StyledAuthComponent in an electron app.

The error 
```
M {code: "auth/unsupported-persistence-type", message: "The current environment does not support the specified persistence type."}
``` 
is shown.

I have created a project to reproduce the error. The following steps can be used to reproduce the error
```
git clone https://github.com/iaaflaafc/react-firebaseui-error.git
cd react-firebaseui-error/
npm install
npm run dev
```

**Comment by bojeil-google** [comment]
Electron is not currently officially supported by Firebase Auth. It is currently treated as a node.js server environment. In node.js server environment, only in memory persistence is supported.

**Comment by iaaflaafc** [comment]
Thanks for replying.

I have a follow-up question.

In the code, I am not explicitly setting authentication state persistence mode.

By default, the persistence type should be set to `firebase.auth.Auth.Persistence.NONE` in the case of Electron ( as it is treated as a node.js server environment ).

I tried setting persistence to `firebase.auth.Auth.Persistence.NONE` using `firebase.auth().setPersistence(firebase.auth.Auth.Persistence.NONE)` but it did not seem to make any difference and error is still being shown.

My question-
Is there any way to set the appropriate persistence mode so that this error is not shown?

**Comment by bojeil-google** [comment]
Hmm, not sure why this is happening. For now, you don't have to set it explicitly. The default and only available behavior should apply. Will try to look into this when I have time to setup an electronjs app.

**Comment by bojeil-google** [comment]
Forgot to give an update on this. Electron is not officially supported (we haven't directly tested that environment). What is happening here is that the underlying firebase-auth SDK is mistaking Electron environment with a Node.js environment where only "In memory" persistence is supported.

**Comment by maxogden** [comment]
I came up with a monkeypatch workaround for anyone else that hits this issue:

```js
// HACK to trick firebase into allowing persistence in electron
if (typeof window !== 'undefined') {
  var orig = firebase.INTERNAL.node
  delete firebase.INTERNAL.node
  firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL)
  firebase.INTERNAL.node = orig
}
```

The browser detection in Firebase doesn't account for electron. It thinks electron is node, and therefore disables the LOCAL persistence option. Should be a really easy fix

**Comment by locohost** [comment]
@maxogden Thanks for posting this Max! It doesn't work for me. I'm building and Electron app that accesses Firestore. I'm setting up sign-in in a new window. In the auth.js page I put your above code right below the `firebase.initializeApp(config);` line. Am I doing anything wrong on missing a step? Thank you!

**Comment by maxogden** [comment]
@locohost Ahh sorry I haven't tested with firebaseui. I'm just using `require('firebase')`. I guess both firebaseui and firebase use the same Firebase Auth module, but I found this issue via google. You could try never doing `firebase.INTERNAL.node = orig;`, but I'm not sure if that will mess anything up.

**Comment by locohost** [comment]
Thank you @maxogden ! I got some other firebase.auth stuff working. Seems like a lot of firebase shi..stuff just doesn't want to work in Electron.

**Comment by jhuleatt** [comment]
Check out this thorough blog post on using Firebase + Electron: https://medium.com/firebase-developers/using-firebase-in-electron-tips-and-tricks-24ac5b44bf5a
