### ISSUE TITLE
Configuring FirebaseUI through StyledFirebaseAuth Component 

### ISSUE THREAD

**Issue by shaibt** [firebase/firebaseui-web-react#32]
Hi,

Need help figuring out how to set the `credentialHelper` when configuring to `firebaseui.auth.CredentialHelper.NONE` (sample code doesn't address this).
Is there a simple way to access the underling firebaseui definitions from the component? 
Other than `import firebaseui from 'firebaseui'` (which I think unnecessarily increases my package size)?
I understand I can access the firebaseui object itself in the `uiCallback` prop but here I need access to the static definitions.

**Comment by nicolasgarnier** [comment]
@shaibt, `react-firebaseui` is just a wrapper on `firebaseui`. `firebaseui` is already imported by `react-firebaseui` so yuor build will contain it. You can import it from your project too, it shouldn't increase the build size.
