### ISSUE TITLE
Question on what is available 

### ISSUE THREAD

**Issue by ChennyBaBy** [firebase/firebaseui-web-react#34]
> FirebaseUI React Components provides React Wrappers on top of the Firebase UI Web library and notably Firebase UI Auth.

Am i right in thinking this project **only** provide wrapper for Firebase Auth currently?

**Comment by nicolasgarnier** [comment]
Yes, currently **FirebaseUI Web** is currently only made of a **Firebase Auth** user interface.

Since **FirebaseUI React** is a react wrapper for **FirebaseUI Web** it has the same feature set which is just **Firebase Auth** :)
