### ISSUE TITLE
 Tl(...).updateCurrentUser is not a function 

### ISSUE THREAD

**Issue by kpennell** [firebase/firebaseui-web-react#37]
Cool lib, thanks! any ideas why I would be getting `Tl(...).updateCurrentUser is not a function`

![image](https://user-images.githubusercontent.com/1060385/42580804-ab4df508-852b-11e8-9d2d-25b2d47d0e15.png)

**Comment by wti806** [comment]
What is the firebase SDK version you are using? It has to be >= 5.0

**Comment by kpennell** [comment]
Yeah, still getting it with that.

**Comment by kpennell** [comment]
"react-firebaseui": "^3.0.4",
 "firebase": "^5.0.0",

**Comment by kpennell** [comment]
npm vs yarn issue?

**Comment by nicolasgarnier** [comment]
I'd post this over to https://github.com/firebase/firebaseui-web since the issue does't seem to be with  firebaseui-web-react (it's just a wrapper for react)

**Comment by mswike** [comment]
Update the script version.
![update](https://user-images.githubusercontent.com/97367945/148666408-018c5d80-9774-4b46-9f5a-2fe9ae5a2cbb.PNG)
