### ISSUE TITLE
Create Typescript type definitions

### ISSUE THREAD

**Issue by marko-asplund** [firebase/firebaseui-web-react#38]
Please publish Typescript type definitions
```
(4,32): Could not find a declaration file for module 'react-firebaseui/StyledFirebaseAuth'. '/Users/me/myproject/node_modules/react-firebaseui/StyledFirebaseAuth.js' implicitly has an 'any' type.
  Try `npm install @types/react-firebaseui` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-firebaseui';`
```

**Comment by SeraphicRav** [comment]
+1

**Comment by SeraphicRav** [comment]
I am still in the prototyping step of my project if it goes into production, I will gladly contribute.

Is there a specific reason to do the PR in DefinitelyTyped rather than here ? For instance, firebaseui-web has it included.

**Comment by marko-asplund** [comment]
I guess Including it in `react-firebaseui` would save users the trouble of having to install it separately. There could also be some maintenance benefits from including it in the main codebase.

**Comment by hoggworks** [comment]
+1

**Comment by nicolasgarnier** [comment]
Yea sure, I'm totally fine including it directly into `react-firebaseui` too :)

**Comment by prontiol** [comment]
Any updates on this?

**Comment by nicolasgarnier** [comment]
I'm still waiting for a volunteer to send a PR :)
