### ISSUE TITLE
Redirect instead of popup

### ISSUE THREAD

**Issue by MatthieuVeillon** [firebase/firebaseui-web-react#4]
Hi, 

Thanks for your work Nicolas. Trying to get it work with redirect flow with a change state. 

I tried signInFlow: 'redirect' but doesn't seems to work. In your "Using FirebaseAuth with a redirect" exemple - the signInFlow is at 'popup'. I assumed 'redirect' would be the right one, am I messing around ? 

Thanks

**Comment by nicolasgarnier** [comment]
Hey @MatthieuVeillon, I have not yet tried with `signInFlow: 'redirect'`. In the example **Using FirebaseAuth with a redirect** I showing how to do a redirect after the sign-in flow is complete but you are right, the sign-in flow is still using popup.

Using `signInFlow: 'redirect'` with a state change *should* still work. Would you have an example online where this doesn't work?

You could also use the `firebase.auth().onAuthStateChanged` listener to check the auth state after the redirect. Actually, in general, it might be good to only draw the UI after the firebase auth state is ready. So wait for `firebase.auth().onAuthStateChanged` to trigger once and then draw the app's UI.

**Comment by Haraldson** [comment]
> You could also use the firebase.auth().onAuthStateChanged listener to check the auth state after the redirect. Actually, in general, it might be good to only draw the UI after the firebase auth state is ready. So wait for firebase.auth().onAuthStateChanged to trigger once and then draw the app's UI.

I’m doing exactly this, but it fails. At no point am I being logged in, not after a refresh, not ever. If I change to `signInFlow: 'popup'`, it works immediately – but this is not recommended on phones.

I think there might be a listener missing in the `<FirebaseAuth>` component? It’s kind of blackboxed, so I’m not sure what else I should do here?

This component is always rendered unless the user is authenticated;

```javascript
import React, { Component } from 'react'
import firebase from 'firebase'
import { FirebaseAuth } from 'react-firebaseui'

export default class SignIn extends Component {
    state = {
        signedIn: false
    }

    uiConfig = {
        signInFlow: 'popup',
        signInOptions: [
            firebase.auth.FacebookAuthProvider.PROVIDER_ID,
            {
                provider: firebase.auth.PhoneAuthProvider.PROVIDER_ID,
                recaptchaParameters: {
                    type: 'image',
                    size: 'normal',
                    badge: 'bottomleft'
                },
                defaultCountry: 'NO'
            }
        ],
        callbacks: {
            signInSuccess: this.onSignInSuccess
        }
    }

    componentDidMount() {
        this.props.auth.onAuthStateChanged(user => {
            if(user)
                this.onSignInSuccess()
        })
    }

    onSignInSuccess = () => {
        this.setState({ signedIn: true })
        return false
    }

    render() {
        if(!this.state.signedIn) {
            return (
                <div id="sign-in">
                    <h1>Please sign in to <strong>Versus</strong></h1>
                    <FirebaseAuth uiConfig={this.uiConfig} firebaseAuth={this.props.auth} />
                </div>
            )
        }

        return ''
    }
}

```

**Comment by nicolasgarnier** [comment]
Can you check that componentDidMount actually fires? and what about the auth state changed observer. Basically could you replace with:

```js
  componentDidMount() {
        console.log('Component Mounted, starting to observe onAuthStateChanged');
        this.props.auth.onAuthStateChanged(user => {
                console.log('New signedIn state', !!user);
                this.setState({ signedIn: !!user })
        })
    }
```

And see what gets logged?

**Comment by Haraldson** [comment]
I’m getting these on both page loads (before and after the redirect):

```console
Component Mounted, starting to observe onAuthStateChanged
New signedIn state false
```

**Comment by nicolasgarnier** [comment]
Strange...

Can you show me how you create the firebase app instance? `this.props.auth`. just want to make sure it's not using a random app name for instance.

On a side note: as per my own testing popup auth actually works well in mobile browsers. You can try this app on a bunch of mobile devices for instance: https://www.friendly-pix.com

**Comment by Haraldson** [comment]
`this.props.auth` is just the initialized Firebase app instance, passed in from the parent component (the React app itself).

Basically just 

```javascript
import Fire from '../fire'
const auth = Fire.auth()

// Then in render()
<SignIn auth={auth} />
```

**Comment by nicolasgarnier** [comment]
I just wanted to make sure the app doesn't have a random name at initialization. For instance: `firebase.initializeApp(config, randomAppName);` If the app name changes between page loads then things won't work properly between pages (Just checking, since it's unlikely that you are doing this anyhow).

**Comment by Haraldson** [comment]
Not passing in any app name, actually. It’s optional in the documentation, but does your implementation rely on it?

**Comment by nicolasgarnier** [comment]
nope it's good that you are not  :)

@bojeil-google do you have any idea? It's strange after the page redirects back the user is not signed-in...

@Haraldson by any chance would you be able to put this non-working example online somewhere? So we could try it out and experience the issue.

**Comment by Haraldson** [comment]
@nicolasgarnier The Facebook Login app isn’t live, I would have to manually add you as a tester to it. PM me your fbid/username if still interested.

**Comment by nicolasgarnier** [comment]
Here it is: https://www.facebook.com/nivco

**Comment by Haraldson** [comment]
And the WIP app: https://nt-kampbattle.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
Thanks @Haraldson.

@bojeil-google > After the redirect flow it looks like the user is signed in the temporary firebaseUI app, but not in the original app. For instance in the app pointed above:

`auth.app.firebase_.app('nt-versus-firebaseui-temp').auth().currentUser` returns a user but `auth.currentUser` is null...

Looks like there is something wrong with the way the temporary app signs-users in the main app after the redirect in react. Not sure what it could be but maybe that rings a bell to you...

**Comment by bojeil-google** [comment]
Not sure yet why this is happening as I can't test it. Can you add my Facebook account as a tester?
https://www.facebook.com/profile.php?id=100010123453643

**Comment by Haraldson** [comment]
@bojeil-google I added you now!

**Comment by bojeil-google** [comment]
Ok, I think I have a theory:
```
      t.prototype.componentDidMount = function() {
            n(221);
            var e = n(222);
            this.firebaseUiWidget = e.auth.AuthUI.getInstance() || new e.auth.AuthUI(this.firebaseAuth),
            this.firebaseUiWidget.reset(), 
            this.firebaseUiWidget.start("#" + this.elementId, this.uiConfig)
        }
```
You are calling `reset()` right after initialization, that is cancelling the previous pending operation. We cancel on reset because for single page apps, reset is used to cancel and restart sign in. So when the UI is shown again on the same page, it doesn't process a previous operation. When you instantiate a new instance, don't call reset immediately after. Call it only when already initialized.

**Comment by Haraldson** [comment]
I never call reset on anything, but maybe the built code does? If so, that’s all happening in the `<FirebaseAuth>` component.

**Comment by nicolasgarnier** [comment]
Yep that's done in `<FirebaseAuth>` let me make an exception for the redirect flow...
I'll publish anew version so you can try it out asap.

**Comment by nicolasgarnier** [comment]
@Haraldson can you try v1.0.10 ? :)

**Comment by nicolasgarnier** [comment]
@bojeil-google if the `reset()` was the culprit would the `nt-versus-firebaseui-temp` app still have the signed-in user?

**Comment by bojeil-google** [comment]
In this case, yes. When the FirebaseUI instance is initialized, the temp app is also initialized which initializes the Auth instance underneath. That is enough for it to complete the sign in with redirect. `reset` does not signOut the user from that temp instance: https://github.com/firebase/firebaseui-web/blob/master/javascript/widgets/authui.js#L441
We could add logic to do so. The risks of dangling auth states are low since we use sessionStorage for that state, so the session will be lost when the window is closed.

**Comment by bojeil-google** [comment]
I think we can signOut from the temp instance on reset. It's not a high priority but I think it is better to do so.

**Comment by Haraldson** [comment]
I updated to v1.0.10, and it works beautifully guys! Thanks for the help. I deployed the updated version in case you want to see for yourselves. :)

**Comment by nicolasgarnier** [comment]
yay! Awesome thanks for checking @Haraldson
