### ISSUE TITLE
Using Firebase Phone number

### ISSUE THREAD

**Issue by khanhnam99** [firebase/firebaseui-web-react#40]
Have you Using Firebase Phone number?

**Comment by nicolasgarnier** [comment]
@khanhnam99 your question is a bit cryptic, can you expand a little bit? :)

If you are asking how to enable phone support you just need to enable it in your Firebase project's console and add the following provider to the list of providers in your config object:

```js
firebase.auth.PhoneAuthProvider.PROVIDER_ID
```

For more details please refer to the `firebaseui-web` documentation: https://github.com/firebase/firebaseui-web#available-providers
