### ISSUE TITLE
No duplicate imports..still getting error

### ISSUE THREAD

**Issue by puretext** [firebase/firebaseui-web-react#42]
`this.unregisterAuthObserver is not a function
    at e.componentWillUnmount (StyledFirebaseAuth.js:1)`

**Using Next.js and demo code:**

`import StyledFirebaseAuth from 'react-firebaseui/StyledFirebaseAuth'`
`import firebase from 'firebase'`

![image](https://user-images.githubusercontent.com/42104266/44980116-c80fe080-af23-11e8-86dc-9ed2ec001684.png)

**Comment by nicolasgarnier** [comment]
@puretext there was a potential race condition in the case where the element was unmounted immediately after it was mounted. I just released v3.0.7 that fixes it. Can you see if it fixes your issue?

**Comment by puretext** [comment]
@nicolasgarnier it does. Thank You
