### ISSUE TITLE
Can't turn off CredentialHelper

### ISSUE THREAD

**Issue by jeremylenz** [firebase/firebaseui-web-react#5]
I'm trying to set credentialHelper to NONE in my uiConfig variable:

`credentialHelper:  firebaseui.auth.CredentialHelper.NONE`

But the component won't mount.  The error is:
`'firebaseui' is not defined  no-undef`

It appears that I don't have access to the 'firebaseui' object, so it can't evaluate the value of firebaseui.auth.CredentialHelper.NONE.

**Comment by nicolasgarnier** [comment]
You'll need a reference to the `firebaseui` module. You can get that by doing:

```js
import firebaseui from 'firebaseui';
```

or

```js
const firebaseui = require('firebaseui');
```

and you also probably need to install the library: `npm install --save firebaseui`
