### ISSUE TITLE
link Multiple Auth Providers

### ISSUE THREAD

**Issue by SkyJedi** [firebase/firebaseui-web-react#50]
is it possible to do this?

**Comment by nicolasgarnier** [comment]
That should come out of the box yes. Just list the Auth provider that you want to display in the config object. Firebase UI takes care of the flows for linking multiple auth providers.

**Comment by AntonioVentilii** [comment]
why was this one closed, it is not working:

<img width="349" alt="Screenshot 2023-08-04 at 07 31 28" src="https://github.com/firebase/firebaseui-web-react/assets/32648800/4fce946c-1a22-4f09-9f94-b892f8eb4565">
