### ISSUE TITLE
inside a PWA ?

### ISSUE THREAD

**Issue by sebastianovide** [firebase/firebaseui-web-react#52]
Has anybody tested it in a PWA ? I've found it having add behaviours: 
if I open the page with a browser, it works on a browser: pop up, login and then reopen the site. But If I save the page as a PWA then it would never close the popup. My only workaround was to use only EmailAuthProvider.

Any ideas ?

**Comment by jthegedus** [comment]
Are you able to make a minimal reproduction example in another repo? I've been using `popup` with the `StyledFirebaseAuth` component successfully in an installed PWA.

My settings:
```javascript
signInFlow: "popup",
signInOptions: [firebase.auth.GoogleAuthProvider.PROVIDER_ID],
```

**Comment by jhuleatt** [comment]
Closing this out until we get a minimal repro.
