### ISSUE TITLE
Error: Cannot find module 'extract-text-webpack-plugin' 

### ISSUE THREAD

**Issue by juanmaguitar** [firebase/firebaseui-web-react#53]
In the `package.json` there are these scripts..

```
 "scripts": {
    "clean": "rm -rf ./public/bundle.* ./src/firebase-config.json ./node_modules",
    "build": "npm run clean && npm run createfirebaseconf; NODE_ENV=production webpack -p;",
    "createfirebaseconf": "firebase setup:web --json > ./src/firebase-config.json",
    "serve": "firebase serve"
  },
```

When doing `npm run build` it will execute `npm run clean` which will remove the folder `node_modules` among other things

Because of this I'm getting this error when doing `npm run build`

```
Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
```

because of course, all dependencies required in `webpack.config.js` (included this `extract-text-webpack-plugin`) are not available anymore on `node_modules`

I've fixed this by simply removing the `./node_modules` part of the script

```
"clean": "rm -rf ./public/bundle.* ./src/firebase-config.json",
```

What was the purpose of this? Am I missing something?

**Comment by paulywill** [comment]
@juanmaguitar Thank you!!!

This was stumping for quite some time. Yes this appears to be an error when testing locally, if removing the `npm_modules` as part if the build no wonder it was not finding the modules over and over again.
