### ISSUE TITLE
Create react app => dialog-polyfill

### ISSUE THREAD

**Issue by jsgcode** [firebase/firebaseui-web-react#6]
Hi.
I have used this component with CRA and it has shown me the following error.

```
./node_modules/firebaseui/dist/npm.js
Module not found: Can't resolve 'dialog-polyfill' in '<proyect-path>\node_modules\firebaseui\dist'
```

Any idea how to solve it?
Greetings.

**Comment by bojeil-google** [comment]
Hey @jsgcode,  are you using the latest version 2.5.0?

**Comment by bojeil-google** [comment]
Can you upgrade and try again? I think there was an issue with dialog-polyfill being a devDependency in 2.5.0. It has been updated to a dependency in 2.5.1.

**Comment by jsgcode** [comment]
Hello, sorry for the delay.
Update the dependencies and it's already working.
Thanks for the help!
