### ISSUE TITLE
How to check each page user is signed in or not in React

### ISSUE THREAD

**Issue by mehuljariwala** [firebase/firebaseui-web-react#60]
Hello Team,

I implement this fantastic feature but i little bit confuse how can i check that user is signed in or not what should i store in local storage which can verify that user already signed in.

Thanks!

**Comment by bojeil-google** [comment]
Please check this answer on stackoverflow: https://stackoverflow.com/questions/37873608/how-do-i-detect-if-a-user-is-already-logged-in-firebase
