### ISSUE TITLE
Using callbacks to trigger actions

### ISSUE THREAD

**Issue by asawyers** [firebase/firebaseui-web-react#61]
Is there a way to use the "callbacks" in the uiConfig object to trigger an action? 

In the example the callback is "signInSuccessWithAuthResult" which sounds like it should be returning something. I would like to access it, or simply use the callback to fire a redux action.

I searched all over this repo and didn't see any documentation on it.

**Comment by asawyers** [comment]
After doing a lot more digging, found the solution in the actual firebase documentation:

callbacks: {
        // Avoid redirects after sign-in.
        signInSuccessWithAuthResult: (authResult, redirectUrl) => {
        // User successfully signed in.
        // Return type determines whether we continue the redirect automatically
        // or whether we leave that to developer to handle.
    
        console.log(authResult, redirectUrl)
        // actions you want go here
        return true;
        },
    }

Maybe consider putting this into the github documentation?

**Comment by philberg** [comment]
@asawyers thank you! I was looking for this and couldn't find it anywhere.
