### ISSUE TITLE
Why is not firebaseui-web for Angular?

### ISSUE THREAD

**Issue by hack2024** [firebase/firebaseui-web-react#62]
Hi!. why there is not a binding for Angular, why for react, this is a joke?

**Comment by bojeil-google** [comment]
For angular applications, you can use this [FirebaseUI Web Angular Wrapper](https://github.com/RaphaelJenni/firebaseui-angular) from the community.

**Comment by hack2024** [comment]
thanks @bojeil-google i will give it a try!
