### ISSUE TITLE
Unable to signOut, redirectStateIsReady_ is undefined

### ISSUE THREAD

**Issue by seethroughtrees** [firebase/firebaseui-web-react#66]
Thanks for the helpful library.

I'm unable to call `firebase.auth().signOut`, because I get an uncaught exception:

```
Uncaught TypeError: Cannot read property 'then' of undefined
    at Object.t.ob (auth.js:868)
    at Object.i [as signOut] (exports_lib.js:198)
```

Tracing auth.js looks like: `this.redirectStateIsReady_` is undefined while the signOut method is expecting a Promise.

Any thoughts are appreciated.

version: 3.1.2
react: 16.8.6

**Comment by wti806** [comment]
@seethroughtrees  Can you provide the code snippet of where you call signOut() to help us debug? You have to initialize firebase App/Auth before making any API calls on Auth.

**Comment by seethroughtrees** [comment]
Thanks so much for the response @wti806 .


I actually just figured it out.   Passing the method as 

``` javascript
{ signOut: firebaseApp.auth().signOut }
``` 

returns the error.  but passing it as an anonymous function:

``` javascript
{ signOut: () => firebaseApp.auth().signOut() }
``` 

preserves the value of this from the line in auth.js, and works perfect.  

Closing the ticket.
