### ISSUE TITLE
Source code for StyledFirebaseAuth

### ISSUE THREAD

**Issue by philberg** [firebase/firebaseui-web-react#68]
It looks like `src/index.js` requires `./StyledFirebaseAuth`, but I can't find it.  Is there a reason it's missing?

I was trying to debug the issue with the emailLink auth method not working

**Comment by apaatsio** [comment]
It's generated by webpack.

https://github.com/firebase/firebaseui-web-react/blob/7f876329656a2a337655383e75d7974993fbbbc2/webpack.config.js#L24-L29

**Comment by philberg** [comment]
Gotcha, thanks
