### ISSUE TITLE
Please upgrade firebaseui dep to v4.0

### ISSUE THREAD

**Issue by whollacsek** [firebase/firebaseui-web-react#69]
Development of [firebaseui](https://github.com/firebase/firebaseui-web) has been active and it is now v4.0. @nicolasgarnier If you have some time it would be great if we can get the latest version. If upgrading to v4.0 is too much of a hassle (there are breaking changes from firebase js sdk) can we at least get the latest v3.x? Thanks!

**Comment by aaronash** [comment]
I'm running into an issue where I get `TypeError: Cannot read property 'PROVIDER_ID' of undefined` when I use `firebase.auth.PhoneAuthProvider.PROVIDER_ID` in the `signInOptions` config, but `new firebase.auth().PhoneAuthProvider` works (which seems to be the old way). Could this be related to outdated dependences? (I'm a JS noob)

**Comment by agrohs** [comment]
Any update/plan on here for firebase 4 updates?

**Comment by jhuleatt** [comment]
[Done](https://github.com/firebase/firebaseui-web-react/pull/75)! Released on npm as [4.0.0](https://www.npmjs.com/package/react-firebaseui/v/4.0.0)
