### ISSUE TITLE
Limit auth to a certain domain 

### ISSUE THREAD

**Issue by pietrop** [firebase/firebaseui-web-react#78]
👋 
I want to limit auth for users from a certain domain eg `@example.com`.

I've seen that I can setup rules in firestore (eg stackoverflow[How do I create firestore rules based on users email domain?](https://stackoverflow.com/questions/49174634/how-do-i-create-firestore-rules-based-on-users-email-domain)) which is great. 

But I was wondering if there was a way to use `setCustomParameters`( as described here [Firebase limit access to certain domains](https://blog.jimmycai.com/p/firebase-limit-access-to-certain-domains/) ) in `firebaseui-web-react`?

```js
var provider = new firebase.auth.GoogleAuthProvider();
provider.setCustomParameters({
    hd: "example.com"
});
```

**Comment by go0dev** [comment]
I found you can use OAuthSignInOption.customParamter.
Here is example.
```
  const uiConfig: firebaseui.auth.Config = {
    signInFlow: 'popup',
    signInSuccessUrl: '/',
    signInOptions: [
      {
        provider: firebase.auth.GoogleAuthProvider.PROVIDER_ID,
        customParameters: {
          hd: 'example.com',
        },
      },
    ],
  };
```
