### ISSUE TITLE
UI widget after signout

### ISSUE THREAD

**Issue by nivethaKumar** [firebase/firebaseui-web-react#79]
![image](https://user-images.githubusercontent.com/34262141/68372245-7d60a880-0166-11ea-831e-d173a6ac6b3e.png)

My requirement is remove the please sign in to localhost:XXXX text or need to redirect the login page
Could you please tell

**Comment by barbalex** [comment]
See: https://github.com/firebase/firebaseui-web-react/issues/67#issuecomment-534718886

You can disable accountchooeser by adding: `credentialHelper: 'none'` in the config object until the bug is fixed.
