### ISSUE TITLE
How can I have Persistent state

### ISSUE THREAD

**Issue by saostad** [firebase/firebaseui-web-react#8]
How can I have Persistent State?
Now I have to do authenticate after every page refresh.

I tried to use firebase docs but it doesn't work for me.

[https://firebase.google.com/docs/auth/web/auth-state-persistence?authuser=0](url)

**Comment by bojeil-google** [comment]
Please provide more information on your environment.

**Comment by saostad** [comment]
this is how I use the component:

`import firebase from 'firebase/app';
import firebaseApp from './services/firebase.config';
import { FirebaseAuth } from 'react-firebaseui';`

And in component class:


`
uiConfig = {
    signInFlow: 'popup',
    signInOptions: [
      firebase.auth.GoogleAuthProvider.PROVIDER_ID,
      firebase.auth.FacebookAuthProvider.PROVIDER_ID,
      firebase.auth.EmailAuthProvider.PROVIDER_ID,
    ],
    callbacks: {
      signInSuccess: () => {
        const user = firebase.auth().currentUser;        
        this.props.actions.userLogIn(user);
        this.props.actions.loadCategories(user.uid);
        return false;
      }
    }
  };
return (
{!this.props.user.signedIn &&
          <div>
            <FirebaseAuth uiConfig={this.uiConfig} 
              firebaseAuth={firebaseApp.auth()}
              />
          </div>
        }
        {this.props.user.signedIn &&
          <p>You Signed In! </p>
        }
);
`

**Comment by bojeil-google** [comment]
Do you even check `onAuthStateChanged` ? FirebaseUI will render whenever it is called even if a user is logged in.

**Comment by saostad** [comment]
actually  I am using redux to check the status of logged in user, and in every successful login I do update the state.
is there any place to look in initial state management to see if user logged in in the past?

**Comment by bojeil-google** [comment]
Please read the documentation on how to determine the state of a user: https://firebase.google.com/docs/auth/web/manage-users

**Comment by saostad** [comment]
Thanks,
this is how it works for me:

```
componentWillMount(){
    const that = this;
    firebaseApp.auth().onAuthStateChanged(function(user) {
      if (user) {
        that.doSignIn();
      }
    });    
  }
```

**Comment by rwieruch** [comment]
For anyone who stumbles upon this, maybe [this](https://www.robinwieruch.de/react-firebase-auth-persistence/) helps.
