### ISSUE TITLE
Getting warning about samesite=none but without secure. Does this mean that this library will break my site when chrome 80 enforces this rule?

### ISSUE THREAD

**Issue by tberghuis** [firebase/firebaseui-web-react#83]
warning text:

> A cookie associated with a resource at http://google.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

**Comment by jhuleatt** [comment]
Hi @tberghuis, please see this comment in the firebase-js-sdk repo for info about that warning: https://github.com/firebase/firebase-js-sdk/issues/2284#issuecomment-669520324
