### ISSUE TITLE
redirectUrl parameter in signInSuccessWithAuthResult is undefined

### ISSUE THREAD

**Issue by aiupjulian** [firebase/firebaseui-web-react#87]
### Describe your environment

  * Operating System version: macOS Catalina 10.15.4
  * Browser version: Google Chrome Version 80.0.3987.162 (Official Build) (64-bit)
  * Firebase UI version: 4.5.0
  * Firebase SDK version: 7.12.0
  * React FirebaseUI version: 4.1.0
  * React version: 16.13.0
  * React router version: 5.1.2

###  Describe the problem

I'm using `signInFlow: 'redirect'`. Trying to create a dynamic URL to redirect to after the user signs in (the page the user was in before starting sign in flow), but when it redirects me back to my site, and `signInSuccessWithAuthResult` gets called, `redirectUrl` is undefined.
I tried with `signInFlow: 'popup'`, but it doesn't work either.

#### Steps to reproduce:

Refer to the code/app below. Sign in with facebook, and after that, you'll get redirected to my site's sign in page, and what I explained before happens (`redirectUrl` is undefined).

#### Relevant Code:
  * [Github](https://github.com/aiupjulian/solidariapp)
  * [Web app](https://solidariapp-93cdb.firebaseapp.com/)

**Comment by bojeil-google** [comment]
This is not what the `redirectUrl` is for. This is a [legacy field](https://github.com/firebase/firebaseui-web#signinsuccesswithauthresultauthresult-redirecturl)

**Comment by aiupjulian** [comment]
First thank you for responding so quick. Do you know a way I can achieve what I need? If I use 'popup' it'll work because the app stays in the background, but I prefer 'redirect', and if I use that I lose the state of my app. I thought I could send the URL to be redirected to the login flow, and that can be returned when someone logs in successfully.

**Comment by bojeil-google** [comment]
Quick solution: save the `redirectUrl` in `sessionStorage` and get it back after.
Or if your app is not a single page app, you can use the legacy solution. You would need to pass `redirectUrl` query parameter in the sign in page URL query string (check docs). When you return back, you can get it via the callback.

**Comment by aiupjulian** [comment]
Sorry man, I didn't understand the docs, I thought that the URL was autogenerated with signInSuccessUrl. Thank you again for your response, stay safe!
